[workspace]
resolver = "3"
members = ["crates/telescope-core", "crates/telescope-app"]

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "MIT"

# GPUI is slow unoptimized; optimize it even in debug builds.
[profile.dev.package]
gpui-pre = { opt-level = 3 }
gpui-component = { opt-level = 3 }
gpui-base = { opt-level = 3 }
gpui-kit = { opt-level = 3 }
gpui-pre-platform = { opt-level = 3 }
taffy = { opt-level = 3 }
rustybuzz = { opt-level = 3 }
ttf-parser = { opt-level = 3 }
